// Package typescript_generator provides TypeScript code generation from proto definitions.
// Supports both gRPC-Web (streaming) and HTTP/REST (gateway) modes.
package typescript_generator

import (
	"fmt"
	"path/filepath"
	"strings"
	"time"

	"github.com/desyang-hub/go-rpc/generators"
)

// TypeScriptPlugin implements the LanguagePlugin interface for TypeScript code generation.
type TypeScriptPlugin struct{}

// NewTypeScriptPlugin creates a new TypeScript language plugin.
func NewTypeScriptPlugin() *TypeScriptPlugin {
	return &TypeScriptPlugin{}
}

// Language returns the language identifier.
func (p *TypeScriptPlugin) Language() string {
	return "typescript"
}

// Description returns a human-readable description.
func (p *TypeScriptPlugin) Description() string {
	return "TypeScript gRPC-Web/HTTP-REST client and React/Vue Hook code generator"
}

// Templates returns all template definitions.
func (p *TypeScriptPlugin) Templates() map[string]string {
	return map[string]string{}
}

// Generate produces TypeScript output files from the parsed proto file.
func (p *TypeScriptPlugin) Generate(config generators.GenConfig, parsed *generators.ProtoFile) ([]generators.GeneratedFile, error) {
	var files []generators.GeneratedFile

	// Determine generation mode
	useGateway := config.Options["generate_gateway"] == "true"

	for _, svc := range parsed.Services {
		pascalName := generators.ToPascalCase(svc.Name)

		if useGateway {
			// Generate HTTP/REST client for gateway mode
			clientContent, err := p.generateGatewayClient(config, parsed, svc)
			if err != nil {
				return nil, fmt.Errorf("generating gateway client for %s: %w", svc.Name, err)
			}
			clientFile := filepath.Join(config.OutputDir, svcToFilename(parsed.Name)+"_"+svcToFilename(svc.Name)+"_rest_client.ts")
			files = append(files, generators.GeneratedFile{
				Path:        clientFile,
				Content:     clientContent,
				Description: "Generated HTTP/REST client (gRPC-Web Proxy)",
			})
		} else {
			// Generate TypeScript gRPC-Web client (original mode)
			clientContent, err := p.generateGrpcWebClient(config, parsed, svc)
			if err != nil {
				return nil, fmt.Errorf("generating TS gRPC-Web client for %s: %w", svc.Name, err)
			}
			clientFile := filepath.Join(config.OutputDir, svcToFilename(parsed.Name)+"_"+svcToFilename(svc.Name)+"_client.ts")
			files = append(files, generators.GeneratedFile{
				Path:        clientFile,
				Content:     clientContent,
				Description: "Generated TypeScript gRPC-Web client",
			})
		}

		// Generate React/Vue Hook if requested
		if config.Options["generate_react"] == "true" {
			hookContent, err := p.generateReactHook(config, parsed, svc)
			if err != nil {
				return nil, fmt.Errorf("generating TS hook for %s: %w", svc.Name, err)
			}
			hookFile := filepath.Join(config.OutputDir, "use"+generators.ToPascalCase(svc.Name)+".hook.ts")
			files = append(files, generators.GeneratedFile{
				Path:        hookFile,
				Content:     hookContent,
				Description: "Generated React Hook",
			})
		}
	}

	return files, nil
}

// generateGrpcWebClient generates a TypeScript gRPC-Web client class.
func (p *TypeScriptPlugin) generateGrpcWebClient(config generators.GenConfig, parsed *generators.ProtoFile, svc generators.Service) (string, error) {
	var b strings.Builder

	timestamp := time.Now().Format(time.RFC3339)
	pascalName := generators.ToPascalCase(svc.Name)

	b.WriteString("// Code generated by rpc-gen. DO NOT EDIT.\n")
	b.WriteString(fmt.Sprintf("// Source: %s.proto\n", parsed.Name))
	b.WriteString(fmt.Sprintf("// Language: %s\n", p.Language()))
	b.WriteString(fmt.Sprintf("// Generated at: %s\n\n", timestamp))
	b.WriteString(fmt.Sprintf("/**\n%s gRPC-Web Client Module\nGenerated TypeScript client for %s service.\n*/\n\n",
		parsed.Name, svc.Name))
	b.WriteString("import { ClientReadableStream, ClientDuplexStream } from 'grpc-web';\n\n")
	b.WriteString(fmt.Sprintf("export interface %sClient {\n", pascalName))

	for _, method := range svc.Methods {
		if method.ServerStream {
			if method.ClientStream {
				b.WriteString(fmt.Sprintf("  %s(stream: ReadableStream<%s>): ClientDuplexStream<%s, %s>;\n",
					method.Name, method.InputType, method.OutputType, method.InputType))
			} else {
				b.WriteString(fmt.Sprintf("  %s(request: %s): ClientReadableStream<%s>;\n",
					method.Name, method.InputType, method.OutputType))
			}
		} else {
			b.WriteString(fmt.Sprintf("  %s(request: %s): Promise<%s>;\n",
				method.Name, method.InputType, method.OutputType))
		}
	}

	b.WriteString("}\n\n")
	b.WriteString(fmt.Sprintf("export class %sClientImpl implements %sClient {\n", pascalName, pascalName))
	b.WriteString("  private readonly hostname: string;\n")
	b.WriteString("  private readonly credentials: {secure: boolean} | undefined;\n")
	b.WriteString(fmt.Sprintf("  private readonly service: %sClient;\n\n", pascalName))
	b.WriteString("  constructor(hostname: string, credentials?: {secure: boolean}) {\n")
	b.WriteString("    this.hostname = hostname;\n")
	b.WriteString("    this.credentials = credentials;\n")
	b.WriteString(fmt.Sprintf("    this.service = new %sClient(hostname, credentials);\n", pascalName))
	b.WriteString("  }\n\n")

	for _, method := range svc.Methods {
		if !method.ServerStream {
			b.WriteString(fmt.Sprintf("  %s(request: %s): Promise<%s> {\n",
				method.Name, method.InputType, method.OutputType))
			b.WriteString(fmt.Sprintf("    return this.service.%s(request);\n", method.Name))
			b.WriteString("  }\n\n")
		}
	}

	b.WriteString("}\n\n")
	b.WriteString(fmt.Sprintf("export function create%sClient(hostname: string, credentials?: {secure: boolean}): %sClient {\n",
		pascalName, pascalName))
	b.WriteString(fmt.Sprintf("  return new %sClientImpl(hostname, credentials);\n}\n", pascalName))

	return b.String(), nil
}

// generateGatewayClient generates an HTTP/REST client for gRPC-Gateway mode.
// This client uses fetch/axios to communicate with the gateway instead of gRPC-Web.
func (p *TypeScriptPlugin) generateGatewayClient(config generators.GenConfig, parsed *generators.ProtoFile, svc generators.Service) (string, error) {
	var b strings.Builder

	timestamp := time.Now().Format(time.RFC3339)
	pascalName := generators.ToPascalCase(svc.Name)
	baseURL := config.Options["gateway_host"] + ":" + config.Options["gateway_port"]
	if baseURL == ":" {
		baseURL = "localhost:8081"
	}

	b.WriteString("// Code generated by rpc-gen. DO NOT EDIT.\n")
	b.WriteString(fmt.Sprintf("// Source: %s.proto\n", parsed.Name))
	b.WriteString(fmt.Sprintf("// Language: %s\n", p.Language()))
	b.WriteString(fmt.Sprintf("// Generated at: %s\n\n", timestamp))
	b.WriteString(fmt.Sprintf("/**\n%s HTTP/REST Client Module\nGenerated client for %s service via gRPC-Gateway.\n*/\n\n",
		parsed.Name, svc.Name))
	b.WriteString("import axios from 'axios';\n")
	b.WriteString("import type { AxiosInstance, AxiosResponse } from 'axios';\n\n")

	// Generate request/response interfaces for each method
	b.WriteString("// ==================== Request/Response Types ====================\n\n")
	for _, method := range svc.Methods {
		b.WriteString(fmt.Sprintf("// %s %s\n", method.Name, method.Comment))
		b.WriteString(fmt.Sprintf("export interface %sRequest {\n", method.InputType))
		// Parse the input fields from proto definition
		b.WriteString(fmt.Sprintf("  // Input type: %s\n", method.InputType))
		b.WriteString("  // Fields defined in proto\n}\n\n")

		b.WriteString(fmt.Sprintf("export interface %sResponse {\n", method.OutputType))
		b.WriteString(fmt.Sprintf("  // Output type: %s\n", method.OutputType))
		b.WriteString("  // Fields defined in proto\n}\n\n")
	}

	// Generate the client class
	b.WriteString(fmt.Sprintf("// ==================== %s HTTP/REST Client ====================\n\n", svc.Name))
	b.WriteString(fmt.Sprintf("export interface %sRestClient {\n", pascalName))
	for _, method := range svc.Methods {
		if !method.ServerStream {
			b.WriteString(fmt.Sprintf("  %s(request: %sRequest): Promise<%sResponse>;\n",
				method.Name, method.InputType, method.OutputType))
		}
	}
	b.WriteString("}\n\n")

	b.WriteString(fmt.Sprintf("export class %s(restBaseURL: string = '%s') {\n", pascalName, baseURL))
	b.WriteString("  private readonly baseUrl: string;\n")
	b.WriteString("  private readonly axios: AxiosInstance;\n\n")
	b.WriteString("  constructor(baseURL: string = '%s') {\n", baseURL))
	b.WriteString("    this.baseUrl = baseURL;\n")
	b.WriteString("    this.axios = axios.create({\n")
	b.WriteString(fmt.Sprintf("      baseURL: baseURL,\n"))
	b.WriteString("      timeout: 30000,\n")
	b.WriteString("      headers: {\n")
	b.WriteString("        'Content-Type': 'application/json',\n")
	b.WriteString("        'Accept': 'application/json',\n")
	b.WriteString("      },\n")
	b.WriteString("    });\n")
	b.WriteString("  }\n\n")

	for _, method := range svc.Methods {
		if !method.ServerStream {
			b.WriteString(fmt.Sprintf("// %s\n", method.Name))
			b.WriteString(fmt.Sprintf("async %s(request: %sRequest): Promise<%sResponse> {\n",
				method.Name, method.InputType, method.OutputType))

			// Determine HTTP method based on naming convention
			httpMethod := "POST"
			path := fmt.Sprintf("/%s/%s/%s", parsed.Package, svc.Name, method.Name)
			if strings.HasPrefix(method.Name, "get") || method.Name == "ping" || method.Name == "exists" {
				httpMethod = "GET"
			}

			b.WriteString(fmt.Sprintf("    const %s = await this.axios.httpMethod(path, { params, data });\n",
				method.Name, httpMethod, path))
			b.WriteString(fmt.Sprintf("    return response.data as %sResponse;\n", method.OutputType))
			b.WriteString("  }\n\n")
		}
	}

	b.WriteString(fmt.Sprintf("  // Health check utility\n"))
	b.WriteString("async healthCheck(): Promise<{ status: string }> {\n")
	b.WriteString("  try {\n")
	b.WriteString("    const response = await this.axios.get(this.baseUrl + '/health');\n")
	b.WriteString("    return { status: response.data.status || 'healthy' };\n")
	b.WriteString("  } catch (error) {\n")
	b.WriteString("    return { status: 'unhealthy' };\n")
	b.WriteString("  }\n")
	b.WriteString("}\n")
	b.WriteString("}\n\n")

	b.WriteString(fmt.Sprintf("export function create%sClient(baseURL: string = '%s'): %sRestClient {\n",
		pascalName, baseURL, pascalName))
	b.WriteString(fmt.Sprintf("  return new %s(baseURL);\n}\n", pascalName))

	return b.String(), nil
}

// generateReactHook generates a React Hook for the service client.
func (p *TypeScriptPlugin) generateReactHook(config generators.GenConfig, parsed *generators.ProtoFile, svc generators.Service) (string, error) {
	var b strings.Builder

	timestamp := time.Now().Format(time.RFC3339)
	pascalName := generators.ToPascalCase(svc.Name)
	hookName := "use" + pascalName
	useGateway := config.Options["generate_gateway"] == "true"

	b.WriteString("// Code generated by rpc-gen. DO NOT EDIT.\n")
	b.WriteString(fmt.Sprintf("// Source: %s.proto\n", parsed.Name))
	b.WriteString("// Language: TypeScript\n")
	b.WriteString(fmt.Sprintf("// Generated at: %s\n\n", timestamp))
	b.WriteString(fmt.Sprintf("/**\nReact Hook for %s service.\n*/\n\n", svc.Name))
	b.WriteString("import { useCallback } from 'react';\n")

	if useGateway {
		b.WriteString(fmt.Sprintf("import { %sRestClient } from './%s_%s_rest_client';\n\n",
			pascalName, generators.ToSnakeCase(parsed.Name), generators.ToSnakeCase(svc.Name)))
	} else {
		b.WriteString(fmt.Sprintf("import { %sClient } from './%s_%s_client';\n\n",
			pascalName, generators.ToSnakeCase(parsed.Name), generators.ToSnakeCase(svc.Name)))
	}

	b.WriteString(fmt.Sprintf("export interface %sHook {\n", hookName))
	for _, method := range svc.Methods {
		if !method.ServerStream {
			b.WriteString(fmt.Sprintf("  %s: (request: %s) => Promise<%s>;\n",
				method.Name, method.InputType, method.OutputType))
		}
	}
	b.WriteString("}\n\n")

	gatewayImport := "restClient"
	if !useGateway {
		gatewayImport = "client"
	}

	b.WriteString(fmt.Sprintf("export function %s(baseURL: string = '%s'): %sHook {\n", hookName, "localhost:8081", hookName))
	if useGateway {
		b.WriteString(fmt.Sprintf("  const restClient = new %s(baseURL);\n\n", pascalName))
	} else {
		b.WriteString(fmt.Sprintf("  const client = %sRestClient(baseURL);\n\n", pascalName))
	}

	b.WriteString("  const call = useCallback((method: keyof " + pascalName + "Client, args: any[]) => {\n")
	b.WriteString("    return (restClient as any)[method](...args);\n")
	b.WriteString("  }, [restClient]);\n\n")

	for _, method := range svc.Methods {
		if !method.ServerStream {
			b.WriteString(fmt.Sprintf("  restClient.%s = useCallback((request: %s): Promise<%s> => {\n",
				method.Name, method.InputType, method.OutputType))
			b.WriteString(fmt.Sprintf("    return call('%s', [request]) as Promise<%s>;\n", method.Name, method.OutputType))
			b.WriteString("  }, [restClient, call]);\n\n")
		}
	}

	b.WriteString(fmt.Sprintf("  return restClient as %sHook;\n", hookName))
	b.WriteString("}\n")

	return b.String(), nil
}

// svcToFilename converts a name to a valid TypeScript filename.
func svcToFilename(name string) string {
	return generators.ToSnakeCase(name)
}
