// Package typescript_generator provides TypeScript code generation from proto definitions.
package typescript_generator

import (
	"fmt"
	"path/filepath"
	"strings"
	"time"

	"go-rpc/generators"
)

// TypeScriptPlugin implements the LanguagePlugin interface for TypeScript code generation.
type TypeScriptPlugin struct{}

// NewTypeScriptPlugin creates a new TypeScript language plugin.
func NewTypeScriptPlugin() *TypeScriptPlugin {
	return &TypeScriptPlugin{}
}

// Language returns the language identifier.
func (p *TypeScriptPlugin) Language() string {
	return "typescript"
}

// Description returns a human-readable description.
func (p *TypeScriptPlugin) Description() string {
	return "TypeScript gRPC-Web client and React Hook code generator"
}

// Templates returns all template definitions.
func (p *TypeScriptPlugin) Templates() map[string]string {
	return map[string]string{}
}

// Generate produces TypeScript output files from the parsed proto file.
func (p *TypeScriptPlugin) Generate(config generators.GenConfig, parsed *generators.ProtoFile) ([]generators.GeneratedFile, error) {
	var files []generators.GeneratedFile

	for _, svc := range parsed.Services {
		// Generate TypeScript client
		clientContent, err := p.generateClient(config, parsed, svc)
		if err != nil {
			return nil, fmt.Errorf("generating TS client for %s: %w", svc.Name, err)
		}
		clientFile := filepath.Join(config.OutputDir, svcToFilename(parsed.Name)+"_"+svcToFilename(svc.Name)+"_client.ts")
		files = append(files, generators.GeneratedFile{
			Path:        clientFile,
			Content:     clientContent,
			Description: "Generated TypeScript gRPC-Web client",
		})

		// Generate React Hook if requested
		if config.Options["generate_react"] == "true" {
			hookContent, err := p.generateReactHook(config, parsed, svc)
			if err != nil {
				return nil, fmt.Errorf("generating TS hook for %s: %w", svc.Name, err)
			}
			hookFile := filepath.Join(config.OutputDir, "use"+generators.ToPascalCase(svc.Name)+".hook.ts")
			files = append(files, generators.GeneratedFile{
				Path:        hookFile,
				Content:     hookContent,
				Description: "Generated React Hook",
			})
		}
	}

	return files, nil
}

// generateClient generates a TypeScript gRPC-Web client class.
func (p *TypeScriptPlugin) generateClient(config generators.GenConfig, parsed *generators.ProtoFile, svc generators.Service) (string, error) {
	var b strings.Builder

	timestamp := time.Now().Format(time.RFC3339)
	pascalName := generators.ToPascalCase(svc.Name)

	b.WriteString("// Code generated by rpc-gen. DO NOT EDIT.\n")
	b.WriteString(fmt.Sprintf("// Source: %s.proto\n", parsed.Name))
	b.WriteString(fmt.Sprintf("// Language: %s\n", p.Language()))
	b.WriteString(fmt.Sprintf("// Generated at: %s\n\n", timestamp))
	b.WriteString(fmt.Sprintf("/**\n%s gRPC-Web Client Module\nGenerated TypeScript client for %s service.\n*/\n\n",
		parsed.Name, svc.Name))
	b.WriteString("import { ClientReadableStream, ClientDuplexStream } from 'grpc-web';\n\n")
	b.WriteString(fmt.Sprintf("export interface %sClient {\n", pascalName))

	for _, method := range svc.Methods {
		if method.ServerStream {
			if method.ClientStream {
				b.WriteString(fmt.Sprintf("  %s(stream: ReadableStream<%s>): ClientDuplexStream<%s, %s>;\n",
					method.Name, method.InputType, method.OutputType, method.InputType))
			} else {
				b.WriteString(fmt.Sprintf("  %s(request: %s): ClientReadableStream<%s>;\n",
					method.Name, method.InputType, method.OutputType))
			}
		} else {
			b.WriteString(fmt.Sprintf("  %s(request: %s): Promise<%s>;\n",
				method.Name, method.InputType, method.OutputType))
		}
	}

	b.WriteString("}\n\n")
	b.WriteString(fmt.Sprintf("export class %sClientImpl implements %sClient {\n", pascalName, pascalName))
	b.WriteString("  private readonly hostname: string;\n")
	b.WriteString("  private readonly credentials: {secure: boolean} | undefined;\n")
	b.WriteString(fmt.Sprintf("  private readonly service: %sClient;\n\n", pascalName))
	b.WriteString("  constructor(hostname: string, credentials?: {secure: boolean}) {\n")
	b.WriteString("    this.hostname = hostname;\n")
	b.WriteString("    this.credentials = credentials;\n")
	b.WriteString(fmt.Sprintf("    this.service = new %sClient(hostname, credentials);\n", pascalName))
	b.WriteString("  }\n\n")

	for _, method := range svc.Methods {
		if !method.ServerStream {
			b.WriteString(fmt.Sprintf("  %s(request: %s): Promise<%s> {\n",
				method.Name, method.InputType, method.OutputType))
			b.WriteString(fmt.Sprintf("    return this.service.%s(request);\n", method.Name))
			b.WriteString("  }\n\n")
		}
	}

	b.WriteString("}\n\n")
	b.WriteString(fmt.Sprintf("export function create%sClient(hostname: string, credentials?: {secure: boolean}): %sClient {\n",
		pascalName, pascalName))
	b.WriteString(fmt.Sprintf("  return new %sClientImpl(hostname, credentials);\n}\n", pascalName))

	return b.String(), nil
}

// generateReactHook generates a React Hook for the service client.
func (p *TypeScriptPlugin) generateReactHook(config generators.GenConfig, parsed *generators.ProtoFile, svc generators.Service) (string, error) {
	var b strings.Builder

	timestamp := time.Now().Format(time.RFC3339)
	pascalName := generators.ToPascalCase(svc.Name)
	hookName := "use" + pascalName

	b.WriteString("// Code generated by rpc-gen. DO NOT EDIT.\n")
	b.WriteString(fmt.Sprintf("// Source: %s.proto\n", parsed.Name))
	b.WriteString("// Language: TypeScript\n")
	b.WriteString(fmt.Sprintf("// Generated at: %s\n\n", timestamp))
	b.WriteString(fmt.Sprintf("/**\nReact Hook for %s service.\n*/\n\n", svc.Name))
	b.WriteString("import { useCallback } from 'react';\n")
	b.WriteString(fmt.Sprintf("import { %sClient } from './%s_%s_client';\n\n",
		pascalName, generators.ToSnakeCase(parsed.Name), generators.ToSnakeCase(svc.Name)))
	b.WriteString(fmt.Sprintf("export interface %sHook {\n", hookName))
	for _, method := range svc.Methods {
		if !method.ServerStream {
			b.WriteString(fmt.Sprintf("  %s: (request: %s) => Promise<%s>;\n",
				method.Name, method.InputType, method.OutputType))
		}
	}
	b.WriteString("}\n\n")
	b.WriteString(fmt.Sprintf("export function %s(hostname: string): %sHook {\n", hookName, hookName))
	b.WriteString(fmt.Sprintf("  const client = %sClient(hostname);\n\n", pascalName))
	b.WriteString("  const call = useCallback((method: keyof " + pascalName + "Client, args: any[]) => {\n")
	b.WriteString("    return (client as any)[method](...args);\n")
	b.WriteString("  }, [client]);\n\n")

	for _, method := range svc.Methods {
		if !method.ServerStream {
			b.WriteString(fmt.Sprintf("  client.%s = useCallback((request: %s): Promise<%s> => {\n",
				method.Name, method.InputType, method.OutputType))
			b.WriteString(fmt.Sprintf("    return call('%s', [request]) as Promise<%s>;\n", method.Name, method.OutputType))
			b.WriteString("  }, [client, call]);\n\n")
		}
	}

	b.WriteString(fmt.Sprintf("  return client as %sHook;\n", hookName))
	b.WriteString("}\n")

	return b.String(), nil
}

// svcToFilename converts a name to a valid TypeScript filename.
func svcToFilename(name string) string {
	return generators.ToSnakeCase(name)
}
