// Package go_generator provides Go code generation from proto definitions.
package go_generator

import (
	"fmt"
	"path/filepath"
	"strings"

	"github.com/desyang-hub/go-rpc/generators"
)

// GoPlugin implements the LanguagePlugin interface for Go code generation.
type GoPlugin struct {
	templates map[string]string
}

// NewGoPlugin creates a new Go language plugin.
func NewGoPlugin() *GoPlugin {
	p := &GoPlugin{}
	p.templates = p.loadTemplates()
	return p
}

// Language returns the language identifier.
func (p *GoPlugin) Language() string {
	return "go"
}

// Description returns a human-readable description.
func (p *GoPlugin) Description() string {
	return "Go gRPC client/server code generator"
}

// Templates returns all template definitions.
func (p *GoPlugin) Templates() map[string]string {
	return p.templates
}

// Generate produces Go output files from the parsed proto file.
func (p *GoPlugin) Generate(config generators.GenConfig, parsed *generators.ProtoFile) ([]generators.GeneratedFile, error) {
	var files []generators.GeneratedFile

	for _, svc := range parsed.Services {
		svcFiles, err := p.generateServiceFiles(config, parsed, svc)
		if err != nil {
			return nil, fmt.Errorf("generating files for service %s: %w", svc.Name, err)
		}
		files = append(files, svcFiles...)
	}

	return files, nil
}

// generateServiceFiles creates all files for a single service.
func (p *GoPlugin) generateServiceFiles(config generators.GenConfig, parsed *generators.ProtoFile, svc generators.Service) ([]generators.GeneratedFile, error) {
	var files []generators.GeneratedFile

	// Build service-specific data for templates
	svcData := map[string]interface{}{
		"service":  svc,
		"proto":    parsed,
		"package":  config.PackageName,
		"language": p.Language(),
	}

	// Generate service client
	engine := generators.NewEngine(generators.EngineConfig{
		OutputDir:   config.OutputDir,
		PackageName: config.PackageName,
		DryRun:      config.DryRun,
	})

	svcContent, err := engine.Render("service_interface", svcData)
	if err != nil {
		return nil, err
	}
	files = append(files, generators.GeneratedFile{
		Path:        filepath.Join(config.OutputDir, svcToFilename(svc.Name)+"_client.go"),
		Content:     svcContent,
		Description: "Generated service client",
	})

	// Generate server stub if requested
	if config.Options["generate_server"] == "true" {
		srvContent, err := engine.Render("server_stub", svcData)
		if err != nil {
			return nil, err
		}
		files = append(files, generators.GeneratedFile{
			Path:        filepath.Join(config.OutputDir, svcToFilename(svc.Name)+"_server.go"),
			Content:     srvContent,
			Description: "Generated server stub",
		})
	}

	return files, nil
}

// loadTemplates returns embedded Go template strings.
func (p *GoPlugin) loadTemplates() map[string]string {
	return map[string]string{
		"service_interface": `// Code generated by rpc-gen. DO NOT EDIT.
// Source: {{.proto.Name}}.proto
// Language: {{.language}}
// Generated at: {{timestamp}}

package {{.package}}

import (
	"context"
	{{range .proto.Imports}}"{{.}}"
	{{end}}
	"google.golang.org/grpc"
)

{{range .proto.Services}}
// {{.Name}}Client is the gRPC client for {{.Name}}.
type {{.Name}}Client struct {
	client {{.Name}}Client
	conn   *grpc.ClientConn
}

// New{{.Name}}Client creates a new {{.Name}} client.
func New{{.Name}}Client(conn *grpc.ClientConn) *{{.Name}}Client {
	return &{{.Name}}Client{
		client: New{{.Name}}Client(conn),
		conn:   conn,
	}
}

{{range .Methods}}
{{if not .ClientStream}}{{if not .ServerStream}}
// {{.Name}} performs a unary RPC call.
func (c *{{.Name}}Client) {{.Name}}(ctx context.Context, in *{{.InputType}}) (*{{.OutputType}}, error) {
	out := new({{.OutputType}})
	err := c.client.{{.Name}}(ctx, in, out)
	return out, err
}
{{end}}{{end}}
{{end}}

// Close closes the underlying connection.
func (c *{{.Name}}Client) Close() error {
	return c.conn.Close()
}

{{end}}

{{end}}`,

		"server_stub": `// Code generated by rpc-gen. DO NOT EDIT.
// Source: {{.proto.Name}}.proto
// Language: {{.language}}

package {{.package}}

import (
	"context"
	"google.golang.org/grpc"
)

{{range .proto.Services}}
// {{.Name}}Server is the server-side interface for {{.Name}}.
type {{.Name}}Server interface {
	{{range .Methods}}
	{{.Name}}(context.Context, *{{.InputType}}) (*{{.OutputType}}, error)
	{{end}}
}

{{end}}`,
	}
}

// svcToFilename converts a service name to a valid Go filename.
func svcToFilename(name string) string {
	return generators.ToSnakeCase(name)
}
