package generators

import (
	"fmt"
)

// GeneratedFile represents a single file generated by a language plugin.
type GeneratedFile struct {
	Path        string
	Content     string
	Description string
}

// GenConfig holds configuration for code generation.
type GenConfig struct {
	ProtoFile   string            // Path to .proto file
	OutputDir   string            // Output directory
	PackageName string            // Go package name for output
	Language    string            // Target language: "go", "python", "typescript"
	DryRun      bool              // Print output instead of writing files
	Options     map[string]string // Language-specific options
}

// LanguagePlugin defines the interface for language code generators.
type LanguagePlugin interface {
	// Language returns the language identifier (e.g., "go", "python", "typescript")
	Language() string

	// Description returns a human-readable description
	Description() string

	// Templates returns a map of template name to template source
	Templates() map[string]string

	// Generate produces output files from the parsed proto file
	Generate(config GenConfig, parsed *ProtoFile) ([]GeneratedFile, error)
}

// PluginRegistry manages language plugin registration and lookup.
type PluginRegistry struct {
	plugins map[string]LanguagePlugin
}

// NewPluginRegistry creates a new plugin registry.
func NewPluginRegistry() *PluginRegistry {
	return &PluginRegistry{
		plugins: make(map[string]LanguagePlugin),
	}
}

// Register adds a language plugin to the registry.
func (r *PluginRegistry) Register(plugin LanguagePlugin) error {
	lang := plugin.Language()
	if _, exists := r.plugins[lang]; exists {
		return fmt.Errorf("language plugin already registered for %s", lang)
	}
	r.plugins[lang] = plugin
	return nil
}

// Get retrieves a language plugin by its identifier.
func (r *PluginRegistry) Get(lang string) (LanguagePlugin, error) {
	plugin, ok := r.plugins[lang]
	if !ok {
		return nil, fmt.Errorf("no plugin registered for language: %s", lang)
	}
	return plugin, nil
}

// List returns all registered language identifiers.
func (r *PluginRegistry) List() []string {
	langs := make([]string, 0, len(r.plugins))
	for lang := range r.plugins {
		langs = append(langs, lang)
	}
	return langs
}

// ─── Plugin Registration Helper ─────────────────────────────────────────

// RegisterDefaultPlugins registers all default language plugins.
// This is the convenience function for typical use cases.
func RegisterDefaultPlugins(registry *PluginRegistry) error {
	panic("Use cli to register plugins manually or import plugins directly")
}
