// Package python_generator provides Python code generation from proto definitions.
package python_generator

import (
	"fmt"
	"path/filepath"
	"strings"
	"time"

	"github.com/desyang-hub/go-rpc/generators"
)

// PythonPlugin implements the LanguagePlugin interface for Python code generation.
type PythonPlugin struct{}

// NewPythonPlugin creates a new Python language plugin.
func NewPythonPlugin() *PythonPlugin {
	return &PythonPlugin{}
}

// Language returns the language identifier.
func (p *PythonPlugin) Language() string {
	return "python"
}

// Description returns a human-readable description.
func (p *PythonPlugin) Description() string {
	return "Python gRPC client code generator"
}

// Templates returns all template definitions.
func (p *PythonPlugin) Templates() map[string]string {
	return map[string]string{}
}

// Generate produces Python output files from the parsed proto file.
func (p *PythonPlugin) Generate(config generators.GenConfig, parsed *generators.ProtoFile) ([]generators.GeneratedFile, error) {
	var files []generators.GeneratedFile

	for _, svc := range parsed.Services {
		content, err := p.generateClient(config, parsed, svc)
		if err != nil {
			return nil, fmt.Errorf("generating Python client for %s: %w", svc.Name, err)
		}

		filename := svcToFilename(parsed.Name) + "_" + svcToFilename(svc.Name) + "_client.py"
		files = append(files, generators.GeneratedFile{
			Path:        filepath.Join(config.OutputDir, filename),
			Content:     content,
			Description: "Generated Python gRPC client",
		})
	}

	return files, nil
}

// generateClient generates a Python gRPC client class.
func (p *PythonPlugin) generateClient(config generators.GenConfig, parsed *generators.ProtoFile, svc generators.Service) (string, error) {
	var b strings.Builder

	timestamp := time.Now().Format(time.RFC3339)

	b.WriteString("# Code generated by rpc-gen. DO NOT EDIT.\n")
	b.WriteString(fmt.Sprintf("# Source: %s.proto\n", parsed.Name))
	b.WriteString(fmt.Sprintf("# Language: %s\n", p.Language()))
	b.WriteString(fmt.Sprintf("# Generated at: %s\n\n", timestamp))
	b.WriteString(fmt.Sprintf("'''\n%s gRPC Client Module\nGenerated Python client for %s service.\n'''\n\n",
		parsed.Name, svc.Name))
	b.WriteString("from typing import Optional, List, Union, Iterator\n")
	b.WriteString("import grpc\n\n")
	pascalName := generators.ToPascalCase(svc.Name)
	b.WriteString(fmt.Sprintf("class %sClient:\n", pascalName))
	b.WriteString(fmt.Sprintf("    '''gRPC client for %s service.'''\n\n", svc.Name))
	b.WriteString("    def __init__(self, channel, timeout=None):\n")
	b.WriteString("        '''\n")
	b.WriteString("        Initialize the client.\n\n")
	b.WriteString("        Args:\n")
	b.WriteString("            channel: gRPC channel for communication\n")
	b.WriteString("            timeout: Default timeout in seconds\n")
	b.WriteString("        '''\n")
	b.WriteString("        self._channel = channel\n")
	b.WriteString("        self._timeout = timeout\n")
	b.WriteString(fmt.Sprintf("        self._stub = %s_Stub(channel)\n\n", pascalName))
	b.WriteString("    def close(self):\n")
	b.WriteString("        '''Close the channel.'''\n")
	b.WriteString("        self._channel.close()\n\n")

	// Generate method stubs
	b.WriteString(fmt.Sprintf("    # %s methods:\n", svc.Name))
	b.WriteString("    # Implement method calls based on your proto definitions\n\n")
	for _, method := range svc.Methods {
		streamType := "unary"
		if method.ServerStream {
			streamType = "server_stream"
		}
		if method.ClientStream {
			streamType = "client_stream"
		}
		b.WriteString(fmt.Sprintf("    def %s(self, request):\n", generators.ToCamelCase(method.Name)))
		b.WriteString(fmt.Sprintf("        '''%s %s call.'''\n", method.Name, streamType))
		b.WriteString(fmt.Sprintf("        # TODO: Implement %s\n", method.Name))
		b.WriteString("        pass\n\n")
	}

	b.WriteString(fmt.Sprintf("__all__ = ['%sClient']\n", pascalName))

	return b.String(), nil
}

// svcToFilename converts a name to a valid Python filename.
func svcToFilename(name string) string {
	return generators.ToSnakeCase(name)
}
